### ISSUE TITLE
Read COG metadata (IFD/tags)

### ISSUE THREAD

**Issue by geospatial-jeff** [geospatial-jeff/async-cog-reader#2]
I'm thinking something like:
```
class Tag:
    ...

class IFD:
    tags: Dict[str, Tag]


class COGTiff:
    fpath: str
    ifds: List[IFD]    

    async def __aenter__(self):
        # Request first 16kb, parse ifd and their tags.
        ifds = <ifd with tags>
        return self(ifds)
```

Usage would be:

```
async with COGTiff('https://coolsat.com/cog.tif') as cog:
    await cog.read_tile()
```

We can reuse most of the code from [COGDumper](https://github.com/mapbox/COGDumper/blob/master/cogdumper/cog_tiles.py) but I'd like to make it more object orientated to make the interface a little easier to use.

I like the `AbstractReader` used by COGDumper, for now lets focus on making it work for http files and then introduce pluggable readers.

**Comment by vincentsarago** [comment]
that's great! 

> We can reuse most of the code from COGDumper but I'd like to make it more object orientated to make the interface a little easier to use.

I had started to do this a while ago. maybe I can find it back !

**Comment by geospatial-jeff** [comment]
As of https://github.com/geospatial-jeff/async-cog-reader/commit/8dfedcdbcf676ab1d5ce4948ba0d2cea84671b38 I think reading metadata is in a good place
