### ISSUE TITLE
Read GeoKeyDirectoryTag into something pyproj compatible

### ISSUE THREAD

**Issue by geospatial-jeff** [geospatial-jeff/async-cog-reader#8]
Everything we need should be in https://github.com/OSGeo/libgeotiff/blob/master/libgeotiff

**Comment by vincentsarago** [comment]
geotiffjs didn't do it either  https://github.com/geotiffjs/geotiff.js/issues/133#issuecomment-598678776

**Comment by geospatial-jeff** [comment]
I quickly realized it wasn't nearly worth it so I decided to just check for epsg code https://github.com/geospatial-jeff/async-cog-reader/commit/c95f1c05ff48410928f57b694bad5bba03f64a8a.  I should add geogcs though.

Good to know I'm not the only one!
